### ISSUE TITLE
isTofX needs to recalculate beta from TOF and pathlength.

### ISSUE THREAD

**Issue by MustafaMustafa** [rnc-lbl/auau200GeVRun14#35]
In StHfCuts, Beta is calculated for primary tracks only, so that information will not be available for all global tracks. We need to recalculate beta for tracks using TOF and pathlength information.

**Comment by MustafaMustafa** [comment]
Hi, Michael, 

The following is a modified version of Xin's code to calculate β for global tracks. You might find it useful to fix this bug (you might want to double check it with Xin once implemented and before committing it to the upstream master). Thank you for working on this. 

   StPicoTrack *t = (StPicoTrack*)mPicoDst->track(i);
    if(!t) continue;                          
                                              
    StDcaGeometry dcaG = t->dcaGeometry();    
    double ptot = dcaG.momentum().mag();      
                                              
    StPhysicalHelixD helix = dcaG.helix();    
                                              
    int index2tof = t->bTofPidTraitsIndex();  
    float beta = 0.;                          
    if(index2tof>=0) {                        
      StPicoBTofPidTraits *tofPid = mPicoDst->btofPidTraits(index2tof);
      if(tofPid)                              
      {                                       
        beta = tofPid->btofBeta();            
                                              
        if(beta<1e-4)                         
        {                                     
          StThreeVectorF btofHitPos = tofPid->btofHitPos();
                                              
          float L = tofPathLength(&eventPrimaryVertex, &btofHitPos, helix.curvature());        
          float tof = tofPid->btof();         
          if(tof>0) beta = L/(tof*(C_C_LIGHT/1.e9));
        }                                                                                                                                                                                                                                      
      }                                       
    }

**Comment by mlomnitz** [comment]
Mustafa and Jochen,
  thanks for the suggestions I will look at ticket. I am also testing with
gMom in HFCuts to see how big statstics improvement is, I suspect it will
be 25-30% increase(? I saw more or less this order difference in the number
of entries with HF code vs older analysis that used gMom).  I will send an
update once jobs have run and I have conclusive results.
Michael

On Fri, Apr 17, 2015 at 11:57 AM, Mustafa Mustafa <notifications@github.com>
wrote:

> Hi, Michael,
>
> The following is a modified version of Xin's code to calculate β for
> global tracks. You might find it useful to fix this bug (you might want to
> double check it with Xin once implemented and before committing it to the
> upstream master). Thank you for working on this.
>
> StPicoTrack *t = (StPicoTrack*)mPicoDst->track(i);
> if(!t) continue;
>
> StDcaGeometry dcaG = t->dcaGeometry();
> double ptot = dcaG.momentum().mag();
>
> StPhysicalHelixD helix = dcaG.helix();
>
> int index2tof = t->bTofPidTraitsIndex();
> float beta = 0.;
> if(index2tof>=0) {
>   StPicoBTofPidTraits *tofPid = mPicoDst->btofPidTraits(index2tof);
>   if(tofPid)
>   {
>     beta = tofPid->btofBeta();
>
>     if(beta<1e-4)
>     {
>       StThreeVectorF btofHitPos = tofPid->btofHitPos();
>
>       float L = tofPathLength(&eventPrimaryVertex, &btofHitPos, helix.curvature());
>       float tof = tofPid->btof();
>       if(tof>0) beta = L/(tof*(C_C_LIGHT/1.e9));
>     }
>   }
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rnc-lbl/auau200GeVRun14/issues/35#issuecomment-94052641>
> .
>



-- 
Michael R. Lomnitz
Ph.D. Candidate in Physics
mlomnitz@kent.edu
309 Smith Hall, Kent OH

**Comment by MustafaMustafa** [comment]
I implemented these functions in my private analysis code:
lines 170-217 here https://github.com/MustafaMustafa/auau200GeVRun14/blob/myAna/StRoot/StPicoD0AnaMaker/StPicoD0AnaMaker.cxx

I am testing now. If it works we can propagate to StHFCuts.

**Comment by MustafaMustafa** [comment]
I did test it and it works. If you guys have no time to propagate the fix to StHFCuts, I can take care of that later tonight.

**Comment by jthaeder** [comment]
Back from WE ... I will do it in the morning

**Comment by tschaume** [comment]
Hey Everyone,

for the record, here a few pointers to the `StV0TofCorrection` class I wrote a while back. It's part of the official STAR CVS in `StBTofUtil` and should take care of what you're trying to achieve here, I think. The latest documentation for `StV0TofCorrection` is in my thesis. You can always find the latest version in the [download](http://star.the-huck.com/download/) section of my analysis page. Alternatively, [here](https://docs.google.com/a/lbl.gov/file/d/0B2Dg5nz9nebjdlg5TDdUQVdTaWs/edit) a direct link to the relevant pages or [here](http://www.star.bnl.gov/webdata/dox/html/classStV0TofCorrection.html) the StRoot online documentation. As a quick start, find [here](http://cgit.the-huck.com/cgit.cgi/StLambdaMaker/tree/) a full usage example for a standard STAR Lambda Analysis.

HTH.

**Comment by jthaeder** [comment]
Code is implemented - waiting in pull request to be added

**Comment by tschaume** [comment]
cool! Added a few comments to the pull request for your consideration.

On April 23, 2015 at 2:27:48 PM, Jochen Thaeder (notifications@github.com) wrote:

Code is implemented - waiting in pull request to be added

**Comment by MustafaMustafa** [comment]
Can we close this ticket now?

**Comment by jthaeder** [comment]
I want to test something more today. Then it can be closed

**Comment by jthaeder** [comment]
Sorry - I forgot to close this one ...
