### ISSUE TITLE
Fix TPC PID

### ISSUE THREAD

**Issue by mlomnitz** [rnc-lbl/auau200GeVRun14#37]
Need to generalize TPC PID, and please spell calculate typo

**Comment by jthaeder** [comment]
fixed in dev master - in the current pull request

**Comment by MustafaMustafa** [comment]
Is this done? Can somebody link to the commit where this was addressed? Thanks,

**Comment by jthaeder** [comment]
This was done in commit
https://github.com/jthaeder/auau200GeVRun14/commit/70f1635a53494c05e31aec6209ad23c6e6e4186
