### ISSUE TITLE
HFCuts failure on failing to open the bad runs list

### ISSUE THREAD

**Issue by MustafaMustafa** [rnc-lbl/auau200GeVRun14#40]
The error message is opposite to what it should be. I also suggest to mention in the message that you are aborting everything. Or, don't abort and issue a warning. 

https://github.com/rnc-lbl/auau200GeVRun14/blob/master/StRoot/StPicoHFMaker/StHFCuts.cxx#L134-L137

**Comment by MustafaMustafa** [comment]
@jthaeder, I can take care of this issue if you don't have time for it. Many people are running into this issue and getting confused and I have to support that. 

I suggest you issue a warning and let the chain continue instead of aborting everything for a missing bad runs list.

**Comment by jthaeder** [comment]
sorry … I will take care of this today
--
Dr. Jochen Thaeder
jochen@thaeder.de

Nuclear Science Division
Lawrence Berkeley National Laboratory
1 Cyclotron Road
Berkeley, CA, 94720
U.S.A.

**Comment by jthaeder** [comment]
This was fixed in https://github.com/rnc-lbl/auau200GeVRun14/pull/60 
- in case of not existing bad run file - warning is issued now and bad runs are not taken into account
