### ISSUE TITLE
Npe Library bug

### ISSUE THREAD

**Issue by mlomnitz** [rnc-lbl/auau200GeVRun14#50]
Hello Kunsu and all, 
  I tried compiling the library with the NPE code in and found a minor bug in StElectronPair.cxx lines 81,85 and 89:

StRoot/StPicoNpeEventMaker/StElectronPair.cxx:81: error: 'lowest' is not a member of 'std::numeric_limits<short int>'

I don't think lowest is allowed in the version of the compiler and should switch these to 'min' or something along those lines.

**Comment by MustafaMustafa** [comment]
Thank you for reporting. 
That has been addressed in the most recent pull request from Kunsu. Please sync your fork with master.
