### ISSUE TITLE
Macro to run NPE analysis template

### ISSUE THREAD

**Issue by MustafaMustafa** [rnc-lbl/auau200GeVRun14#55]
Hello @kunsuoh,

Can you also provide a macro to run the NPE analysis code?
Something similar to https://github.com/rnc-lbl/auau200GeVRun14/blob/master/StRoot/macros/runPicoD0AnaMaker.C

**Comment by kunsuoh** [comment]
Yes, I agree, but, I think I need the NPE tree directory name such as "../d0tree/picodsts/..". After starting production, then some NPE tree samples are produced, I will add NPE analysis macro.

**Comment by MustafaMustafa** [comment]
I agree. Thanks. 
I have just started submitted jobs for the production (testing on 60M events). The production will be placed at
/project/projectdirs/starprod/hft/npeTree/Run14/AuAu/200GeV/physics2/P15ic

**Comment by MustafaMustafa** [comment]
Hello, Kunsu, 

Would you also be kind and make a nice README file as in https://github.com/rnc-lbl/auau200GeVRun14/tree/master/StRoot/StPicoD0AnaMaker ?

This will make it easier for you, less questions from people on how to run ;-)

**Comment by kunsuoh** [comment]
I added macro and README file for NPE analysis template with pull request #66

**Comment by MustafaMustafa** [comment]
Thank you!
