### ISSUE TITLE
Update classdef for PicoD0Event

### ISSUE THREAD

**Issue by ajentsch** [rnc-lbl/auau200GeVRun14#57]
QAInfo:You are using STAR_LEVEL : SL15c, ROOT_LEVEL : 5.34.09_1 and node : pdsf7
root4star [0]
Processing runPicoD0AnaMaker.C("test.list","test_out")...
strangeArrayNames-arrayNames-__NARRAYS__ = 0
 loading of shared libraries done
StInfo:  Read in picoDst file /project/projectdirs/starprod/picodsts/Run14/AuAu/200GeV/physics2/P15ic/131/15131052/st_physics_15131052_raw_4000026.picoDst.root
StInfo:  Total 1 files have been read in.
StInfo: StPicoD0AnaMaker - Adding :/project/projectdirs/starprod/hft/d0tree/Run14/AuAu/200GeV/physics2/P15ic/131/15131052/st_physics_15131052_raw_4000026.picoD0.root
Warning in <TStreamerInfo::BuildCheck>:
   The StreamerInfo of class StPicoD0Event read from file /project/projectdirs/starprod/hft/d0tree/Run14/AuAu/200GeV/physics2/P15ic/131/15131052/st_physics_15131052_raw_4000026.picoD0.root
   has the same version (=1) as the active class but a different checksum.
   You should update the version to ClassDef(StPicoD0Event,2).
   Do not try to write objects with the current class definition,
   the files will not be readable.

Warning in <TStreamerInfo::CompareContent>: The following data member of
the in-memory layout version 1 of class 'StPicoD0Event' is missing from
the on-file layout version 1:
   StThreeVector<float> mKfVertex; //
Warning in <TStreamerInfo::CompareContent>: The following data member of
the in-memory layout version 1 of class 'StPicoD0Event' is missing from
the on-file layout version 1:
   int mNKaonPion; //
Warning in <TStreamerInfo::CompareContent>: The following data member of
the in-memory layout version 1 of class 'StPicoD0Event' is missing from
the on-file layout version 1:
   int mNKaons; //
Warning in <TStreamerInfo::CompareContent>: The following data member of
the in-memory layout version 1 of class 'StPicoD0Event' is missing from
the on-file layout version 1:
   int mNPions; //
Warning in <TStreamerInfo::CompareContent>: The following data member of
the in-memory layout version 1 of class 'StPicoD0Event' is missing from
the on-file layout version 1:
   TClonesArray* mKaonPionArray; //
StQAInfo: =================================================================================
StQAInfo: QAInfo:Chain              StChain::bfcChain             Ast = 21.57        Cpu = 18.79
StQAInfo: QAInfo:Maker     StPicoD0AnaMaker::picoD0AnaMaker       Ast =  6.83(31.6%) Cpu =  6.60(35.1%)
StQAInfo: QAInfo:Maker       StPicoDstMaker::picoDstMaker         Ast = 14.75(68.4%) Cpu = 12.19(64.9%)
StInfo:  StPicoD0AnaMaker - writing data and closing output file
StInfo: --------------Error Codes-------------------------
StInfo:      nStOK   nStWarn    nStEOF    nStErr  nStFatal
StInfo:      14540         0         0         0         0
StInfo: --------------------------------------------------
               StMemStat::Summary(calls)        Min        Aver         Max         RMS
=============================================================================================

This is the end of ROOT -- Goodbye

**Comment by jthaeder** [comment]
Hi Mustafa,

I was just sitting with Alex to get the D0AnaMaker running over physics2 D0 trees following your howto.
The classdef of the StPicoD0Event might have to be updated.

**Comment by MustafaMustafa** [comment]
You are probably using the wrong version of the code. You are reading  a
physics2 production, are you sure you have the latest version of the code?

**Comment by ajentsch** [comment]
running "git pull master origin" fixed the issue (it updated the code). I
did not do this last night because I am assumed (incorrectly) that the code
was downloaded in its updated state (since I downloaded it for the first
time last night). Thanks for the help.

Alex

Alexander M. Jentsch, Graduate Student
Relativistic Heavy Ion Physics Department
The University of Texas at Austin
1 University Station C1600
Austin, Texas 78712-0264

Office: RLM 10.310
Phone (cell): 281-726-0114

**Comment by MustafaMustafa** [comment]
Good.

I think you didn't follow the instructions in the README carefully. One of
the commands is to clone the old code not the new one.

**Comment by ajentsch** [comment]
I followed the exact instructions written here:

https://github.com/rnc-lbl/auau200GeVRun14/tree/master/StRoot/StPicoD0AnaMaker



Alexander M. Jentsch, Graduate Student
Relativistic Heavy Ion Physics Department
The University of Texas at Austin
1 University Station C1600
Austin, Texas 78712-0264

Office: RLM 10.310
Phone (cell): 281-726-0114

**Comment by MustafaMustafa** [comment]
I think you applied the third command by accident not noticing the comment.

# If you want to use D0 trees produced for the pico production I (tagged
physics as ooposed to physics2 for production II).
cd auau200GeVRun14
git checkout v1.0
cd ..

I am glad it all works for you now.

**Comment by ajentsch** [comment]
Oh, I just saw that line extended past the text box. My browser cut that
part of the comment off. Thank you for the help. If there is anything I can
do to help with any development, let me know. I would  be happy to be able
to contribute in any way I can.

Alex

Alexander M. Jentsch, Graduate Student
Relativistic Heavy Ion Physics Department
The University of Texas at Austin
1 University Station C1600
Austin, Texas 78712-0264

Office: RLM 10.310
Phone (cell): 281-726-0114

**Comment by MustafaMustafa** [comment]
Hi Alex, 

Thank you for using and testing the code. Yes, we would love more help with the library, I guess you will be attending the analysis meeting? Let us talk fact-to-face there.

**Comment by ajentsch** [comment]
Mustafa,

You mean the collaboration meeting next week? I will be there most of
Monday (until about 2:45 when I have to head back to STAR for shift) and
the same on Tuesday. I fly back to Austin on Wednesday morning.



Alexander M. Jentsch, Graduate Student
Relativistic Heavy Ion Physics Department
The University of Texas at Austin
1 University Station C1600
Austin, Texas 78712-0264

Office: RLM 10.310
Phone (cell): 281-726-0114
