### ISSUE TITLE
Update DoAnaMaker howto

### ISSUE THREAD

**Issue by jthaeder** [rnc-lbl/auau200GeVRun14#58]
https://github.com/rnc-lbl/auau200GeVRun14/blob/master/StRoot/StPicoD0AnaMaker/README.md

I think you have to add the https git clone for users which don't have a github account and their pub key uploaded.

**Comment by MustafaMustafa** [comment]
Fixed in 93f769b3cca2b94d739de341a25b77a36b421552
Thanks @jthaeder
