### ISSUE TITLE
Errors in StPicoD0AnaMaker.cxx -- Stemming from changes in StHfCuts?

### ISSUE THREAD

**Issue by ajentsch** [rnc-lbl/auau200GeVRun14#83]
I am getting the following errors when trying to run the AnaMaker:

StRoot/StPicoHFMaker/StHFCuts.h:22:43: error: StPicoCutsBase/StPicoCutsBase.h: No such file or directory
In file included from .sl64_gcc447/obj/StRoot/StPicoD0AnaMaker/StPicoD0AnaMaker.cxx:18:
StRoot/StPicoHFMaker/StHFCuts.h:29: error: expected class-name before '{' token
StRoot/StPicoHFMaker/StHFCuts.h: In member function 'virtual void StHFCuts::init()':
StRoot/StPicoHFMaker/StHFCuts.h:38: error: 'initBase' was not declared in this scope
.sl64_gcc447/obj/StRoot/StPicoD0AnaMaker/StPicoD0AnaMaker.cxx: In member function 'virtual Int_t StPicoD0AnaMaker::Make()':
.sl64_gcc447/obj/StRoot/StPicoD0AnaMaker/StPicoD0AnaMaker.cxx:114: error: 'class StHFCuts' has no member named 'isGoodEvent'
.sl64_gcc447/obj/StRoot/StPicoD0AnaMaker/StPicoD0AnaMaker.cxx: In member function 'bool StPicoD0AnaMaker::isGoodPair(const StKaonPion*) const':
.sl64_gcc447/obj/StRoot/StPicoD0AnaMaker/StPicoD0AnaMaker.cxx:173: error: 'class StHFCuts' has no member named 'isGoodTrack'
.sl64_gcc447/obj/StRoot/StPicoD0AnaMaker/StPicoD0AnaMaker.cxx:173: error: 'class StHFCuts' has no member named 'isGoodTrack'
.sl64_gcc447/obj/StRoot/StPicoD0AnaMaker/StPicoD0AnaMaker.cxx:174: error: 'class StHFCuts' has no member named 'isTPCKaon'
.sl64_gcc447/obj/StRoot/StPicoD0AnaMaker/StPicoD0AnaMaker.cxx:174: error: 'class StHFCuts' has no member named 'isTPCPion'

The errors are coming from sections of the maker that are not in the "user analysis" area. I have the updated versions of all of the code. Was there a change in StHFCuts that did not get propagated to the AnaMaker?

**Comment by MustafaMustafa** [comment]
Hi Alex,

StHfCuts has been split into a base class and specialized class. Can you
use link to the base class and compile again?

ln -s `pwd`/auau200GeVRun14/StRoot/StPicoCutsBase StRoot


You also need to add this line to your macro:
https://github.com/rnc-lbl/auau200GeVRun14/blob/master/StRoot/macros/runPicoD0AnaMaker.C#L29

--Mustafa

**Comment by ajentsch** [comment]
That fixed it. Thanks, Mustafa.

**Comment by MustafaMustafa** [comment]
Sure.
