### ISSUE TITLE
StPicoCutsBase::isGoodEvent default parameter value

### ISSUE THREAD

**Issue by MustafaMustafa** [rnc-lbl/auau200GeVRun14#84]
Hi Jochen, 

The default parameter should be specified at declaration in the header file. 
https://github.com/rnc-lbl/auau200GeVRun14/blob/master/StRoot/StPicoCutsBase/StPicoCutsBase.cxx#L137

Using isGoodEvent without specifying aEventCuts result in a compilation error when default parameter is specified in the implementation file.

**Comment by jthaeder** [comment]
Indeed - I will fix it

**Comment by jthaeder** [comment]
fixed in  15589b7
