### ISSUE TITLE
How about adding StPicoDstMaker in here?

### ISSUE THREAD

**Issue by plexoos** [rnc-lbl/auau200GeVRun14#89]
Do you guys plan to incorporate the StPicoDstMaker/ module into this repository? It would help with automatic builds and pull requests for StPicoDstMaker.

**Comment by MustafaMustafa** [comment]
Hi Dmitri,

Yes, we are planning to do that very soon.

**Comment by plexoos** [comment]
I created a separate branch for the StPicoDstMaker module and a pull request  https://github.com/rnc-lbl/auau200GeVRun14/pull/90 to merge it. The history of changes has been preserved and if Xin has an account on github proper credits can be displayed.

**Comment by plexoos** [comment]
The code from StPicoDstMaker has been pushed to rnc-lbl/star-picoDst
